name : 'Custsom GitHub Action'
description : 'A github Actgion that takes an input and returns the square of the number'
inputs:
  num:
    required : true
    default: "1"
outputs:
  num_squared:
    value : ${{ steps.get-square.outputs.num_squared }}
runs:
  using : "composite"
  steps :
   - name : install python
     uses : actions/setup-python@v4
     with :
       python-version : "3.11"
   - name : Install Dependencies
     run : pip installl -r requirement.txt
     shell : bash
   - name: Pass Inputs to Shell
     run : |
       echo "INPUT_NUM=${{}}" >> $GITHUB_ENV
     shell : bash
   - name: Fetch the number square
     id: get-square
     run : python src/get_num_square.py
     shell : bash
